# Generated by Django 5.1.1 on 2024-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=700, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
