# Generated by Django 5.1.1 on 2024-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=700, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=700, null=True)),
                ('location_name', models.CharField(blank=True, max_length=700, null=True)),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=700, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=700, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=700, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=700, null=True)),
                ('refferd_by', models.CharField(blank=True, max_length=700, null=True)),
                ('address', models.CharField(blank=True, max_length=700, null=True)),
                ('zip', models.CharField(blank=True, max_length=700, null=True)),
                ('city', models.CharField(blank=True, max_length=700, null=True)),
                ('state', models.CharField(blank=True, max_length=700, null=True)),
                ('hoa', models.CharField(blank=True, max_length=700, null=True)),
                ('plot_plan', models.CharField(blank=True, max_length=700, null=True)),
                ('hardscape_2d_3d', models.FloatField(blank=True, null=True)),
                ('hardscape_and_planting', models.FloatField(blank=True, null=True)),
                ('above_plan_plus', models.FloatField(blank=True, null=True)),
                ('measuring_for_site_plan', models.FloatField(blank=True, null=True)),
                ('property_droning', models.FloatField(blank=True, null=True)),
                ('property_survey', models.FloatField(blank=True, null=True)),
                ('consultations_and_revisions_amount_hour', models.IntegerField(blank=True, null=True)),
                ('other', models.FloatField(blank=True, null=True)),
                ('describe_other', models.CharField(blank=True, max_length=700, null=True)),
                ('project_amount', models.FloatField(blank=True, null=True)),
                ('payment_option', models.CharField(blank=True, max_length=700, null=True)),
                ('amount_to_charge_for_credit_card', models.FloatField(blank=True, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=700, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=700, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('billing_zip_code', models.CharField(blank=True, max_length=700, null=True)),
                ('cvv', models.CharField(blank=True, max_length=700, null=True)),
                ('amount_to_charge_for_zelle', models.FloatField(blank=True, null=True)),
                ('amount_to_charge_for_cash', models.FloatField(blank=True, null=True)),
                ('amount_to_charge_for_check', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('representative_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
