# Generated by Django 5.1.1 on 2025-02-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_location_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('email', models.CharField(blank=True, max_length=700, null=True)),
                ('phone', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='check_number',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='client_signature_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='client_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='expiration_date_str',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_phone_name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='representative_signature_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='representative_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='secondary_phone_name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project_id',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='submitted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(blank=True, max_length=700, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=700, null=True)),
                ('expiration_time', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=700, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=700, null=True)),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to_id', models.CharField(blank=True, max_length=700, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=700, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='api.contact')),
            ],
            options={
                'unique_together': {('contact', 'category', 'name')},
            },
        ),
    ]
