# Generated by Django 5.1.1 on 2025-02-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_contact_archived_contact_check_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='expiration_time',
            new_name='expiration_date',
        ),
    ]
