# Generated by Django 5.1.1 on 2025-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_expiration_time_creditcard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
