# Generated by Django 5.1.1 on 2025-05-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tasktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropBoxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='end_choices',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='is_progress',
            field=models.BooleanField(default=True),
        ),
    ]
